[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686-unknown-bare_metal.json"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[profile.dev]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
