[package]
name = "os_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#compiler_builtins = { git = "https://github.com/rust-lang/compiler-builtins" }
#rlibc = "1.0.0"
